"""access_control

Revision ID: 4accc0ee70c6
Revises: 4998b8ca885d
Create Date: 2026-03-19 18:10:27.923686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4accc0ee70c6'
down_revision: Union[str, Sequence[str], None] = '4998b8ca885d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('groups', 'enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'enabled')
    # ### end Alembic commands ###
