"""add message_id clip_start clip_end to download_log

Revision ID: 7ac692c4c515
Revises: 3fa1e9b0c2d5
Create Date: 2026-03-19 13:30:13.560309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac692c4c515'
down_revision: Union[str, Sequence[str], None] = '3fa1e9b0c2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_log', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.add_column('download_log', sa.Column('clip_start', sa.Integer(), nullable=True))
    op.add_column('download_log', sa.Column('clip_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_log', 'clip_end')
    op.drop_column('download_log', 'clip_start')
    op.drop_column('download_log', 'message_id')
    # ### end Alembic commands ###
