"""initial schema

Revision ID: dc8a66b6a71f
Revises: 
Create Date: 2026-03-17 09:39:07.804932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8a66b6a71f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('url_domain', sa.String(length=253), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_type_created', 'events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_events_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('file_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index('idx_file_cache_expires', 'file_cache', ['expires_at'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('auto_grant_role', sa.Enum('owner', 'admin', 'moderator', 'user', 'restricted', 'banned', name='userrole'), nullable=False),
    sa.Column('allow_pm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limits',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'window')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'moderator', 'user', 'restricted', 'banned', name='userrole'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('quality', sa.String(length=32), nullable=False),
    sa.Column('codec', sa.String(length=16), nullable=False),
    sa.Column('container', sa.String(length=8), nullable=False),
    sa.Column('proxy_enabled', sa.Boolean(), nullable=False),
    sa.Column('keyboard', sa.String(length=8), nullable=False),
    sa.Column('subs_enabled', sa.Boolean(), nullable=False),
    sa.Column('subs_auto', sa.Boolean(), nullable=False),
    sa.Column('subs_always_ask', sa.Boolean(), nullable=False),
    sa.Column('subs_lang', sa.String(length=8), nullable=False),
    sa.Column('split_size', sa.BigInteger(), nullable=False),
    sa.Column('nsfw_blur', sa.Boolean(), nullable=False),
    sa.Column('mediainfo', sa.Boolean(), nullable=False),
    sa.Column('send_as_file', sa.Boolean(), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=False),
    sa.Column('ban_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cookies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain')
    )
    op.create_table('download_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_download_log_user', 'download_log', ['user_id', 'created_at'], unique=False)
    op.create_table('thread_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'thread_id')
    )
    op.create_table('user_group_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('role_override', sa.Enum('owner', 'admin', 'moderator', 'user', 'restricted', 'banned', name='userrole'), nullable=True),
    sa.Column('allow_pm_override', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_policies')
    op.drop_table('thread_policies')
    op.drop_index('idx_download_log_user', table_name='download_log')
    op.drop_table('download_log')
    op.drop_table('cookies')
    op.drop_table('users')
    op.drop_table('rate_limits')
    op.drop_table('groups')
    op.drop_index('idx_file_cache_expires', table_name='file_cache')
    op.drop_table('file_cache')
    op.drop_index('idx_events_user_created', table_name='events')
    op.drop_index('idx_events_type_created', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
