#!/usr/bin/env python3
"""
Export browser cookies to Netscape format and optionally upload to yoink-bot.

Flow:
  1. Launch system Chromium with remote debugging on port 9222
  2. Print the CDP URL - open it in your desktop browser to control remotely
  3. Navigate to target site, log in manually via remote session
  4. Press Enter here when done - cookies are dumped and saved
  5. Optionally POST to bot API

Usage:
  python scripts/export_cookies.py --site youtube.com
  python scripts/export_cookies.py --site instagram.com --upload
  python scripts/export_cookies.py --site youtube.com --upload --bot-url http://localhost:8081 --token TOKEN
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

CHROMIUM_PATH = os.environ.get("CHROMIUM_PATH", "/usr/bin/chromium")
CDP_PORT = int(os.environ.get("CDP_PORT", "9222"))

SITE_URLS: dict[str, str] = {
    "youtube.com":   "https://www.youtube.com",
    "instagram.com": "https://www.instagram.com",
    "twitter.com":   "https://twitter.com",
    "x.com":         "https://x.com",
    "tiktok.com":    "https://www.tiktok.com",
    "vk.com":        "https://vk.com",
    "facebook.com":  "https://www.facebook.com",
    "twitch.tv":     "https://www.twitch.tv",
}


def to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by yoink-bot export_cookies.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0))
        if expires <= 0:
            expires = int(time.time()) + 86400 * 365
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def upload_to_bot(domain: str, content: str, bot_token: str, owner_id: int, bot_url: str) -> bool:
    """Upload cookie content directly via bot API sendDocument."""
    import tempfile
    import urllib.request
    import urllib.parse

    tmp = Path(tempfile.mktemp(suffix=".txt", prefix=f"{domain}_"))
    try:
        tmp.write_text(content, encoding="utf-8")

        # Use multipart form upload via urllib (no extra deps)
        boundary = "---YoinkBotCookieUpload"
        caption = f"/cookie {domain}"

        with open(tmp, "rb") as f:
            file_data = f.read()

        body = (
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="chat_id"\r\n\r\n{owner_id}\r\n'
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="caption"\r\n\r\n{caption}\r\n'
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="document"; filename="{domain}.txt"\r\n'
            f"Content-Type: text/plain\r\n\r\n"
        ).encode() + file_data + f"\r\n--{boundary}--\r\n".encode()

        url = f"{bot_url.rstrip('/')}{bot_token}/sendDocument"
        req = urllib.request.Request(
            url,
            data=body,
            headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
            return result.get("ok", False)
    except Exception as e:
        print(f"  Upload error: {e}", file=sys.stderr)
        return False
    finally:
        tmp.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export browser cookies via CDP remote")
    parser.add_argument("--site", required=True, help="Domain to export (e.g. youtube.com)")
    parser.add_argument("--upload", action="store_true", help="Upload cookies to bot via API")
    parser.add_argument("--bot-url", default=os.environ.get("TELEGRAM_BASE_URL", "http://localhost:8081/bot"), help="Bot API base URL")
    parser.add_argument("--token", default=os.environ.get("BOT_TOKEN"), help="Bot token")
    parser.add_argument("--owner-id", type=int, default=int(os.environ.get("OWNER_ID", "0")), help="Owner Telegram user ID")
    parser.add_argument("--out", help="Save Netscape file to path (default: <site>.txt)")
    parser.add_argument("--cdp-port", type=int, default=CDP_PORT, help=f"CDP remote debug port (default: {CDP_PORT})")
    parser.add_argument("--chromium", default=CHROMIUM_PATH, help=f"Chromium executable (default: {CHROMIUM_PATH})")
    args = parser.parse_args()

    domain = args.site.lstrip(".")
    if not domain:
        print("Error: --site is required", file=sys.stderr)
        sys.exit(1)

    start_url = SITE_URLS.get(domain, f"https://{domain}")
    out_path = Path(args.out) if args.out else Path(f"{domain}.txt")

    print(f"\n  yoink-bot cookie exporter")
    print(f"  Site    : {domain}")
    print(f"  URL     : {start_url}")
    print(f"  Chromium: {args.chromium}")
    print(f"  CDP port: {args.cdp_port}")
    print()

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("Error: playwright not installed. Run: pip install playwright", file=sys.stderr)
        sys.exit(1)

    import socket
    import subprocess
    import shutil
    import tempfile
    import urllib.request

    # Determine server IP
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("1.1.1.1", 80))
        server_ip = s.getsockname()[0]
        s.close()
    except Exception:
        server_ip = "127.0.0.1"

    profile_dir = Path(tempfile.mkdtemp(prefix="ck_profile_"))
    cmd = [
        args.chromium,
        "--headless=new",
        f"--remote-debugging-port={args.cdp_port}",
        "--remote-debugging-address=0.0.0.0",
        f"--user-data-dir={profile_dir}",
        "--no-sandbox",
        "--disable-gpu",
        "--disable-dev-shm-usage",
        start_url,
    ]

    print(f"  Launching Chromium on port {args.cdp_port}...")
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    # Wait for CDP to be ready
    for _ in range(30):
        try:
            urllib.request.urlopen(f"http://127.0.0.1:{args.cdp_port}/json", timeout=1)
            break
        except Exception:
            time.sleep(0.5)
    else:
        print("  Error: Chromium did not start in time.", file=sys.stderr)
        proc.terminate()
        shutil.rmtree(profile_dir, ignore_errors=True)
        sys.exit(1)

    print(f"\n  Remote session ready.")
    print(f"  Chromium binds CDP only on 127.0.0.1 (security restriction in headless mode).")
    print(f"  Forward the port from your desktop first:")
    print(f"    ssh -L {args.cdp_port}:127.0.0.1:{args.cdp_port} <user>@{server_ip}")
    print(f"  Then open in your desktop browser:")
    print(f"    http://127.0.0.1:{args.cdp_port}")
    print(f"  Log into {domain}, then come back here and press Enter.\n")

    try:
        input("  [Press Enter when logged in] ")
    except KeyboardInterrupt:
        print("\n  Cancelled.")
        proc.terminate()
        shutil.rmtree(profile_dir, ignore_errors=True)
        sys.exit(0)

    # Collect cookies via CDP
    print("\n  Collecting cookies...")
    site_cookies: list[dict] = []
    try:
        with sync_playwright() as p:
            browser = p.chromium.connect_over_cdp(f"http://127.0.0.1:{args.cdp_port}")
            ctx = browser.contexts[0] if browser.contexts else browser.new_context()
            cookies = ctx.cookies()
            site_cookies = [c for c in cookies if domain in c.get("domain", "")]
            browser.close()
    except Exception as e:
        print(f"  Warning: could not collect cookies via CDP: {e}", file=sys.stderr)

    proc.terminate()
    shutil.rmtree(profile_dir, ignore_errors=True)

    if not site_cookies:
        print(f"  Warning: no cookies found for {domain}. Are you logged in?")
    else:
        print(f"  Found {len(site_cookies)} cookies for {domain}.")

    netscape = to_netscape(site_cookies)
    out_path.write_text(netscape, encoding="utf-8")
    print(f"  Saved: {out_path} ({out_path.stat().st_size} bytes)")

    if args.upload:
        if not args.token:
            print("  Error: --token or BOT_TOKEN env required for upload", file=sys.stderr)
            sys.exit(1)
        if not args.owner_id:
            print("  Error: --owner-id or OWNER_ID env required for upload", file=sys.stderr)
            sys.exit(1)
        print(f"  Uploading to bot...")
        ok = upload_to_bot(domain, netscape, args.token, args.owner_id, args.bot_url)
        if ok:
            print(f"  Uploaded successfully.")
        else:
            print(f"  Upload failed - cookie saved locally at {out_path}")
            sys.exit(1)

    print()


if __name__ == "__main__":
    main()
